name: Build and publish 

on:
  push:
    branches:
      - main
      - develop
      - feature/**

jobs:  
  build_publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Publish image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/head/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ secrets.GHCR_USERNAME_LOWER }}/devops_project:latest .

      - name: Log in to Github Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Push image to GHCR
        run: docker push ghcr.io/${{ secrets.GHCR_USERNAME_LOWER }}/devops_project:latest