name: FastAPI, Build and Test

on:
  push:
    branches:
      - main
      - develop
      - feature/**

jobs:
  format:
    name: Black and Bandit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip 
          pip install black bandit -r requirements.txt

      - name: Check black on all files
        run: make black_check

      - name: Check security in the project
        run: make bandit

  test:
    name: Run some tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: make test

  qualimetry:
    name: View quality of code with sonarqube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: ''

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.projectKey=devops_project
            -Dsonar.host.url=http://0.0.0.0:9000/
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}


  build:
    name: Build Dockerfile
    runs-on: ubuntu-latest
    env:
      ENV: dev
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: make docker-build #TODO Changer la commande pour avoir les variables d'environnement dédiées
