name: Add instance with terraform

on:
  push:
    branch: 
      - main
      - feature/*

jobs:
  terraform:
    name: Create an EC2 instance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hasicorp/setup-terraform@v3

      - name: Init Terraform
        uses: terraform init

      - name: Plan Terraform
        uses: terraform plan

      - name: Apply Terraform
        uses: terraform apply
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_aws_region: ${{ secrets.TF_VAR_aws_region }}
          TF_VAR_instance_type: ${{ secrets.TF_VAR_instance_type }}
          TF_VAR_key_name: ${{ secrets.TF_VAR_key_name }}
          TF_VAR_key_public: ${{ secrets.TF_VAR_key_public }}
          TF_VAR_my_ip_address: ${{ secrets.TF_VAR_my_ip_address }}