name: Add instance with terraform

on:
  push:
    branches: 
      - main

jobs:
  terraform:
    name: Create an EC2 instance
    runs-on: ubuntu-latest
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_aws_region: ${{ secrets.TF_VAR_aws_region }}
      TF_VAR_instance_type: ${{ secrets.TF_VAR_instance_type }}
      TF_VAR_key_name: ${{ secrets.TF_VAR_key_name }}
      TF_VAR_key_public: ${{ secrets.TF_VAR_key_public }}
      TF_VAR_my_ip_address: ${{ secrets.TF_VAR_my_ip_address }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Fmt Terraform
        working-directory: ./terraform
        run: terraform fmt -check

      - name: Validate Terraform
        working-directory: ./terraform
        run: terraform validate

      - name: Plan Terraform
        working-directory: ./terraform
        run: terraform plan

      - name: Apply Terraform
        working-directory: ./terraform
        run: terraform apply -auto-approve
